### ISSUE TITLE
wrong about mapred/TaskCompletionEvent and mapreduce/TaskCompletionEvent

### ISSUE THREAD

**Issue by haolidong** [cwensel/cascading#60]
Exception in thread "main" java.lang.VerifyError: Inconsistent stackmap frames at branch target 83
Exception Details:
  Location:
    cascading/stats/hadoop/HadoopStepStats.captureDetail(Lcascading/stats/CascadingStats$Type;)V @83: aload_0
  Reason:
    Type '[L**org/apache/hadoop/mapred/TaskCompletionEvent**;' (current frame, locals[4]) is not assignable to '[L**org/apache/hadoop/mapreduce/TaskCompletionEvent**;' (stack map, locals[4])
  Current Frame:
    bci: @77
    flags: { }
    locals: { 'cascading/stats/hadoop/HadoopStepStats', 'cascading/stats/CascadingStats$Type', 'org/apache/hadoop/mapreduce/Job', integer, '[Lorg/apache/hadoop/mapred/TaskCompletionEvent;' }
    stack: { integer }
  Stackmap Frame:
    bci: @83
    flags: { }
    locals: { 'cascading/stats/hadoop/HadoopStepStats', 'cascading/stats/CascadingStats$Type', 'org/apache/hadoop/mapreduce/Job', integer, '[Lorg/apache/hadoop/mapreduce/TaskCompletionEvent;' }
    stack: { }

**Hadoop version: 2.8.0**

**Comment by fs111** [comment]
Can you check the release notes if they changed the class hierarchy between the mapred and mapreduce packages in one of the JIRAs? It looks like they did, which is very bad.

Back in the old times there was only mapred, later they added mapreduce, but the mapreduce classes are not sub-types of mapred, but the other way around. This is very confusing, but a given. I suspect something broke that in 2.8.

Also, could you paste the full StackTrace? It usually helps.

**Comment by haolidong** [comment]
So should I down hadoop to a lower version?

**Comment by fs111** [comment]
yes, 2.7x or 2.6.x should work just fine

**Comment by cwensel** [comment]
If you continue to have issues, can you confirm you are using the `cascading-hadoop2-mr1-x.y.z.jar` and not `cascading-hadoop-x.y.z.jar`?

**Comment by haolidong** [comment]
Yeah, you're right. My problem is solved, thanks!

**Comment by cwensel** [comment]
Sorry, which issue solved your problem. Downgrading Hadoop version, or using the hadoop2 jar?

**Comment by haolidong** [comment]
using the hadoop2 jar
