### ISSUE TITLE
S3Tap parses bucket names incorrectly

### ISSUE THREAD

**Issue by external-torx** [cwensel/cascading#63]
Using an aws endpoint and, separately, an s3 URL of the form s3://my_tenant:my-bucket (including underscores)

In the S3Tap constructor (line 824 in my version) this line is causing problems:
`this.bucketName = identifier.getHost();`

The URI host is null. However the URI authority contains 'my_tenant:my-bucket', which is the full name of the bucket I need to access.

**Comment by cwensel** [comment]
please move this issue over to the cascading-local project, there is no S3Tap here.
