### ISSUE TITLE
Possible to keep java8 on 4.5 release?

### ISSUE THREAD

**Issue by hazel-sudz** [cwensel/cascading#83]
hey @cwensel any chance we could keep java8 on the 4.5 branch at least? AWS EMR 6.X (latest release) still defaults on java8 for the hadoop3 flavors and it would be much appreciated to keep this support before they drop it. I would imagine that EMR is a very common use case for this type of library.

**Comment by cwensel** [comment]
Curious, is the jvm configurable on startup? Is it unstable on Java 11?

The Hadoop requirement is to compile Hadoop on Java 8, but it should theoretically run fine on Java 11. Unsurprised if that isn't true. 

We can revert, but I really was hoping to start leveraging Java 11 without introducing yet another concurrent version.

**Comment by hazel-sudz** [comment]
it's possible to override but it's just not the default out of the box on AWS EMR and I would imagine there could be some breaking assumptions that would be a huge pain to deal with. 

```
Java 8 is the default Java Virtual Machine (JVM) for cluster instances created using Amazon EMR release version 5.0.0 or later. 
```

https://docs.aws.amazon.com/emr/latest/ReleaseGuide/configuring-java8.html

I have have no doubt that hadoop itself works fine on java11. If it's a dealbreaker that's fine just would be more convenient in a managed runtime.

**Comment by cwensel** [comment]
Fair enough, I'll revert the build version.

**Comment by hazel-sudz** [comment]
thank you @cwensel if this is pushed to say 4.6/4.7 I think that is reasonable. I would assume that newer release labels from AWS EMR will be java11+ within a year or so.
