### ISSUE TITLE
Casting issue in PropertyUtil

### ISSUE THREAD

**Issue by conrosebraugh** [cwensel/cascading#94]
I am encountering an issue when running unit tests in a custom library that has Cadence as a dependency. [This block of code](https://github.com/cwensel/cascading/blob/4.5/cascading-core/src/main/java/cascading/property/PropertyUtil.java#L102-L107) has an issue when casting a Class to a String. The call to the PropertyUtil function is coming from [AppProps.getApplicationJarClass](https://github.com/cwensel/cascading/blob/4.5/cascading-core/src/main/java/cascading/property/AppProps.java#L113). Here is the stack trace:

`java.lang.ClassCastException: java.lang.Class cannot be cast to java.lang.String
    at cascading.property.AppProps.getApplicationJarClass(AppProps.java:113)
    at cascading.flow.hadoop.planner.HadoopPlanner.initialize(HadoopPlanner.java:166)
    at com.anon.cascading_ext.flow.LoggingHadoopPlanner.initialize(LoggingHadoopPlanner.java:75)
    at com.anon.cascading_ext.flow.LoggingFlowConnector.connect(LoggingFlowConnector.java:68)
    at cascading.flow.FlowConnector.connect(FlowConnector.java:421)
    at cascading.flow.FlowConnector.connect(FlowConnector.java:270)
    at cascading.flow.FlowConnector.connect(FlowConnector.java:215)
    at cascading.flow.FlowConnector.connect(FlowConnector.java:197)
    at com.anon.formats.mapred.inputformat.TestDirectoryLineInputFormat.testGetCurrentTapSourcePath(TestDirectoryLineInputFormat.java:61)
`

This could be solved by checking if defaultValue is an instance of String and using the Class.toString function. My org is in the process of upgrading from a very old version of Cascading to Cascading 4.5.0. In the version that we are using, [AppProp.getApplicationJarClass actually passes a null Class object as the default value](https://github.com/cwensel/cascading/blob/2.5.0/cascading-core/src/main/java/cascading/property/AppProps.java#L96-L107). 

Is there a recommended method of fixing this casting issue?

Running into this on JDK 8, Cascading 4.5.0

**Comment by cwensel** [comment]
Do you think #96 will resolve this?

**Comment by conrosebraugh** [comment]
I don't. Tested with the following:

`public void testCasting() {
    Object o = Integer.class;
    String s = (String) o;
    System.out.println(s);
  }`

Got this error: `java.lang.ClassCastException: java.lang.Class cannot be cast to java.lang.String`

**Comment by conrosebraugh** [comment]
Deleted a dumb response that I had earlier, hopefully that didn't bug you too much. Yes, that seems like it would solve the issue. Thanks so much for the prompt response!

**Comment by cwensel** [comment]
excellent, when/if the tests pass, i'll merge into wip-4.5 so you can test locally. 

if that works, I can push a 4.5.1 release into maven.

**Comment by cwensel** [comment]
try this release
https://github.com/cwensel/cascading/packages/694992

**Comment by conrosebraugh** [comment]
What is the repository for these wip releases that I should be checking? Doesn't appear to be in maven central

**Comment by conrosebraugh** [comment]
What maven repository can I find these wip releases in?

**Comment by cwensel** [comment]
All wip releases are hosted by Github. 

https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-apache-maven-registry

it's a real pain, but I think i'd be violating sonatype rules if I published wips there, haven't looked at publishing to sonatype snapshot repo. #85

**Comment by conrosebraugh** [comment]
I added the following to the pom file for my project:

```
<repositories>
    <repository>
      <id>github</id>
      <url>https://maven.pkg.github.com/cwensel/cascading</url>
      <snapshots>
        <enabled>true</enabled>
      </snapshots>
    </repository>
  </repositories>
```

And I get a `401: Unauthorized` error when Maven tries to download the dependency.

```
[ERROR] Failed to execute goal on project cascading_tools: Could not resolve dependencies for project com.anon:cascading_tools:jar:2.0-SNAPSHOT: Failed to collect dependencies at net.wensel:cascading-hadoop3-common:jar:4.5.1-wip-26: Failed to read artifact descriptor for net.wensel:cascading-hadoop3-common:jar:4.5.1-wip-26: Could not transfer artifact net.wensel:cascading-hadoop3-common:pom:4.5.1-wip-26 from/to github (https://maven.pkg.github.com/cwensel/cascading): authentication failed for https://maven.pkg.github.com/cwensel/cascading/net/wensel/cascading-hadoop3-common/4.5.1-wip-26/cascading-hadoop3-common-4.5.1-wip-26.pom, status: 401 Unauthorized -> [Help 1]
```

**Comment by cwensel** [comment]
This is expected.

This is the resolution
https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-apache-maven-registry#authenticating-to-github-packages

**Comment by conrosebraugh** [comment]
@cwensel The proposed change fixed the issue that I was having. Thanks for your patience and sharing that documentation. Let me know when the 4.5.1 release is public. Thanks so much!

**Comment by cwensel** [comment]
@conrosebraugh 4.5.1 was published
https://central.sonatype.com/search?q=g:net.wensel&smo=true
